name: Build Openwrt

on: 
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schdule:
#    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Install Dependencies
        run: | 
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Clone Source Code
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          cd lede
          ./scripts/feeds update -a && ./scripts/feeds install -a
                  
      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        # Send connection info to Telegram (optional)
        # You can find related documents here: https://core.telegram.org/bots
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Custom Configuration
        run: |
          [ -e $GITHUB_WORKSPACE/config ] && mv $GITHUB_WORKSPACE/config lede/.config
          cd lede

      - name: Build Process
        id: build
        run: |
          make download -j8 V=s
          find dl -size -1024c -exec ls -l {} \;
          make -j$(nproc) || make -j1 || make -j1 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@main
        if: steps.build.outputs.status == 'success'
        with:
          name: Firmware Test
          path: lede/bin